### PR TITLE
gds2proto: read a GDS file, write a raw geometry proto file

### PR DESCRIPTION
**Pull request by growly**
Eager for comments! I think this works.

Example usage:
```
$ cargo run --  -v -i ~/src/skywater-pdk/libraries/sky130_fd_sc_hd/latest/cells/dfxtp/sky130_fd_sc_hd__dfxtp_1.gds -o /tmp/test
[...]
read: "/home/aryap/src/skywater-pdk/libraries/sky130_fd_sc_hd/latest/cells/dfxtp/sky130_fd_sc_hd__dfxtp_1.gds"
GdsStats { libraries: 1, structs: 1, boundaries: 144, paths: 0, struct_refs: 0, array_refs: 0, text_elems: 10, nodes: 0, boxes: 0 }
wrote: "/tmp/test"
```

Example sanity check:
```
$ protoc -Ilayout21protos/proto --decode=vlsir.raw.Library layout21protos/proto/raw.proto </tmp/test
domain: "sky130_fd_sc_hd__dfxtp_1"
units: NANO
cells {
  name: "sky130_fd_sc_hd__dfxtp_1"
  layout {
    name: "sky130_fd_sc_hd__dfxtp_1"
    shapes {
      layer {
        number: 236
      }
      rectangles {
        lower_left {
        }
        width: 7360
        height: 2720
      }
    }
    shapes {
      layer {
        number: 67
        purpose: 44
      }
      rectangles {
        lower_left {
          x: 2905
          y: -85
        }
        width: 170
        height: 170
      }
      rectangles {
        lower_left {
          x: 3825
          y: -85
        }
        width: 170
        height: 170
      }
[...]
```

### CODE REVIEW

**Comment by dan-fritchman** [comment]
Looking great. 

Couple thoughts: 

* Can we add a (very basic) test or two? 
  * The program may not be rocket-science, but we will wanna know if it fails if (and when), say, the APIs it uses change. 
  * Not clear we'd want to test through the command-line interface. Using `cargo test` is quite nice, including the fact it tests *all* layout21 crates at once. Perhaps we wanna organize like:

```rust
/// Program entry point - parse options, and call the real action 
fn main() {
  let options = ProgramOptions::parse();
  do_the_real_stuff(&options);
}

/// the real action 
fn do_the_real_stuff(&options) {
  // ... do the real stuff ... 
}

#[test]
fn test1() {
  let options = ProgramOptions { /* create via literal, rather than via CLI parsing */ };
  do_the_real_stuff(&options);
  assert!(/* stuff about what happened */);
}
```

* Where - 
  * (a) `do_the_real_stuff` can of course get a "real" name
  * (b) tests would check (at minimum) whether `do_the_real_stuff` crashed
  * Checking files were created etc is even nicer if we care (gds21 has quite a few tests to this effect). But mostly wanna add a smoke-test against the APIs it uses breaking. 

--- 

* The `clap` CLI library looks quite slick. Furthering its slickness, adding some field comments on the `Program` struct's fields appears to propagate them into the help generated with `-h`, such as: 

```rust 
#[derive(Parser)]
struct ProgramOptions {
    /// Docstring here shows up in the `-h` help for the `gds` field
    #[clap(short = 'i', long, default_value = "")]
    // ... 
}
```

Yields 

```
$ cargo run -- -h                                                                 
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `/Users/dan/dev/dan/Layout21/target/debug/gds2proto -h`
gds2proto 

USAGE:
    gds2proto [OPTIONS]

OPTIONS:
    -h, --help             Print help information
    -i, --gds <GDS>        Docstring here shows up in the `-h` help for the `gds` field [default: ]
    # ...
```

---

* Last, there's a handful of `layout21` methods you've essentially rolled your own versions of here. (And I suspect they were the hard part.) We can talk through whether to move to them.

**Comment by dan-fritchman** [comment]
```rust 
    #[test]
    fn dan_wanted_a_test() {
        println!("dan would like a test")
    }
}
```

(Slightly) better test: you could just copy one of the GDS files in `gds21/resources` or `layout21raw/resources`, and check that running `_main` on it produces the same proto-binary every time.

**Comment by growly** [comment]
That's the proto-fragile end-to-end test that I wrote about in my last comment. I take it you agree with that direction, then?

**Comment by dan-fritchman** [comment]
Yeah sorry, right on time I overhauled that comment. 
Had only seen the "smoke test" (which is not *entirely* useless BTW), and missed your commentary above. 

In short: agree, go for it.

**Comment by dan-fritchman** [comment]
I'll also note: the stuff I am mid-writing (e.g. d3e2e73 - for net-label vs `Polygon` intersection tests) will also effect that golden data. 

We can merge that in after the fact; let's get this one done first.

**Comment by growly** [comment]
PTAL

**Comment by dan-fritchman** [comment]
Visiting: https://www.urbandictionary.com/define.php?term=PTAL

**Comment by dan-fritchman** [comment]
Code looks great.  
Personally woulda been fine also using the `resource` function/ directory instead of all the `tempdir` magic. But the latter's a nice upgrade! 

And not sure why it's not showing up here - but the test fails in CI.  
https://github.com/dan-fritchman/Layout21/actions/runs/1781463623. 
Appears due to forgetting to add the test-data files. 

You wanna add those and get this merged?

**Comment by growly** [comment]
> The following paths are ignored by one of your .gitignore files:
> gds2proto/resources

:raised_eyebrow:

**Comment by dan-fritchman** [comment]
Ah yes, that in fact ties into the usage of `resources` as the output-directory for these temp-result-files.  
It's set to be git-ignored for exactly that reason, requiring a `git add -f` to actually add stuff. 

And for whatever reason, CI results show up here in the PR conversation now.  
https://github.com/dan-fritchman/Layout21/actions/runs/1785252761

Looks great, let's get this stuff merged.

**Pull request merged**
